### ISSUE TITLE
Open with selection is not working

### ISSUE THREAD

**Issue by ivilla-clickup** [intellibar/main#6]
**When trying to use "Open with selection" on my computer, it will not actually open.**

- I have tried using both the keyboard shortcut and the option in the menu bar, but neither of them work.
- I believe this has something to do with the accessibility permissions. 
- I tested it on a second computer, and when I switched on the "Open with selection" option, I was given a popup to grant access.
- However, this popup was not visible in the first computer.
- I have also tried manually adding Intellibar in accessibility permissions and restarting, but it still does not work.

Let me know if there are any additional details or things you need tested.

**Comment by astoilkov** [comment]
Hi. What's your OS version? What's the OS version of the other computer?

Also, we can try something (sometimes removing it from Accessibility fixes this issue):
1. Go to System Settings → Privacy & Security → Accessibility and remove IntelliBar from there
2. Restart your computer
3. Go to IntelliBar settings and toggle the checkbox
<img width="557" alt="CleanShot 2023-08-10 at 09 31 32@2x" src="https://github.com/intellibar/main/assets/884810/0b1e9c5f-9960-4c8b-86a0-a23ded3c8c66">

**Comment by ivilla-clickup** [comment]
OS: Ventura: 13.5

I tried those steps with no luck. After restarting, I came back to the option. It was still on from before the reboot. Toggling on and off triggered nothing, and neither the keyboard nor the option in the toolbar worked after.

**Comment by astoilkov** [comment]
Ok, we have your error on our error reporting. I can guess it's you because it's the only error concerning open with selection, it's the first time this error appears, and it has been fired only in the past 2 days. 

I truly don't know what's happening. I will describe to you what I know and you can think of something that might be causing it (maybe something specific to your computer — may be other software interfering).

We have a binary written in Swift that simulates ⌘C in the currently opened app and then we send the clipboard data to IntelliBar and open the window. When running the binary it fails with an error SIGKILL and this is why it fails. I don't know how this is possible.

In the meantime, I've improved the error reporting so I can learn more about the error when we release the new update.

**Comment by ivilla-clickup** [comment]
My best guess is that this is a work computer i'm testing this on and maybe there is something that the IT software is blocking. But also strange since I've tried other apps like Beam and Alfred which are able to grab the text from the currently opened app. I can wait for update to see if the logs turn up better data as well. Thanks!

**Comment by astoilkov** [comment]
Hmm, that makes sense. Ok, let's wait for the better log data and I will dive deep after that. Thanks!
